### ISSUE TITLE
spell error in the readme usage sample

### ISSUE THREAD

**Issue by hailincai** [akamai/cli-purge#12]
In the readme.md, usage section, current content is

## Usage

```
akamai purge [global flags] command [--cpcode --tag] [URLs/CPCodes/Cache Tags...]
```

I think it should be 
## Usage

```
akamai-purge [global flags] command [--cpcode --tag] [URLs/CPCodes/Cache Tags...]
```
The real command is akamai-purge, not the akmai with the purge option. It really confuse me when I try to execute the cli tool at first time.

**Comment by dshafik** [comment]
@hailincai you are correct if you are using it as a stand-alone tool, but the [recommended way to install](https://github.com/akamai/cli-purge#install) is to first install [Akamai CLI](https://developer.akamai.com/cli) and then to install the purge package with `akamai install purge`. 

This would then make the calls `akamai purge` as documented.
