### ISSUE TITLE
readme.md has wrong default value for --section

### ISSUE THREAD

**Issue by hailincai** [akamai/cli-purge#13]
In the current readme.MD file, I see this

--section value — Section of the credentials file (default: "default") [$AKAMAI_EDGERC_SECTION]

But really when I run the tool, the default section the tool look is the ccu section.

**Comment by ciinema** [comment]
that fact confused me over a hour, u need the "ccu" section in .edgerc

**Comment by fr-yunho** [comment]
confusing me too

**Comment by kporowski** [comment]
Thanks for your contribution. I am closing the issue now.
