### ISSUE TITLE
'akamai purge invalidate' with no args is misleading

### ISSUE THREAD

**Issue by stuartio** [akamai/cli-purge#14]
If the user fails to supply a --cpcode or --url option then the command does not error out. Instead it says purging... and hangs, suggesting (which is alarming) that it is purging ALL cpcodes/urls, when in fact it isn't doing anything as it lacks the necessary input.

**Comment by dshafik** [comment]
In this case, it is waiting for a list of URLs fed in via `STDIN`, and defaults to purging URLs. I will look into adding a message noting this to avoid the confusion. Thanks!

**Comment by dshafik** [comment]
The next release will show this (the second line):

<img width="529" alt="image 2019-03-04 at 12 32 29 pm" src="https://user-images.githubusercontent.com/58074/53761120-95ff1d00-3e79-11e9-8421-7a0a33856da1.png">
