### ISSUE TITLE
Add support for purge by Edge-Cache-Tag

### ISSUE THREAD

**Issue by ueuktfd** [akamai/cli-purge#3]
CCUv3 API supports purge by Edge-Cache-Tag. Would be great to have it in cli-purge too

**Comment by dshafik** [comment]
@ueuktfd this is next on our list, it should be a simple addition

**Comment by dshafik** [comment]
This has been added and is included in [v1.0.0](https://github.com/akamai/cli-purge/releases/tag/1.0.0)
