### ISSUE TITLE
Support for network flag to select staging

### ISSUE THREAD

**Issue by rogertetzlaff** [akamai/cli-purge#6]
It appears the full akamai CLI supports a global flag for --network (default value is "production", optional value is "staging"). There does not appear to be a way to specify the network in the akamai-purge utility. Thanks!

**Comment by justinrummel** [comment]
You can use the `--staging` flag at the end

```
jrummel@res-mpiff ~> akamai purge delete -h
Incorrect Usage: flag: help requested

Name:
   akamai purge delete

Usage:
   akamai purge delete [command options] [URL]... or [CP Code]... or [Cache Tag]...

Flags:
   --cpcode  Purge by CPCode
   --tag         Purge by cache tag
   --production  (default)
   --staging
```

**Comment by justinrummel** [comment]
Here is the code that begins to define the `--staging` flag

https://github.com/akamai/cli-purge/blob/master/command.go#L38-L40

**Comment by dshafik** [comment]
I'm going to close this issue as the feature exists and has been mentioned above.
