### ISSUE TITLE
akamai purge list show helps reference for akamai dns

### ISSUE THREAD

**Issue by ericdebeij** [akamai/cli-purge#7]
Small copy-paste error. The command:

> akamai purge list

will tell you to get help for akamai **dns**

> See "akamai **dns** help [command]" for details.

Which probably should be slightly different

**Comment by justinrummel** [comment]
Thanks @ericdebeij let me see if I can get this looked at.

**Comment by dshafik** [comment]
Fixed in [cli-common-golang: ff6f30c42c8085fd68075856b429649d4a711f40](https://github.com/akamai/cli-common-golang/commit/ff6f30c42c8085fd68075856b429649d4a711f40). 

It'll be included in the next release.

Thanks for your report!
