### ISSUE TITLE
Support use of a proxy server

### ISSUE THREAD

**Issue by tim70z** [akamai/cli-purge#9]
Hi, I am utilizing the akamai-cli to kick off a purge but it appears to not be honoring / inheriting the --proxy directive. The akamai-cli root functions work fine via proxy but my attempts of incorporating it with the purge command are resulting in:

No help topic for (proxy server name is returned)

This is the convention I am using:
**./akamai --proxy <proxy name|ip+port> purge --section default invalidate --cpcode xxxxxx**

**Comment by ahyear** [comment]
Hello,

sorry for reponing but any news on supporting proxy?

**Comment by michaelcw02** [comment]
I was actually having the same issue and found how to use **`purge`** with proxy `proxy` from [here](https://github.com/akamai/cli/search?q=HTTP_PROXY)

Basically, you just have to set environment variables and it will automatically detect them 

```
For CMD: 
set HTTP_PROXY=http://yourproxy.domain.com:1234
set http_proxy=http://yourproxy.domain.com:1234

For PowerShell:
$env:HTTP_PROXY='http://yourproxy.domain.com:1234'
$env:http_proxy='http://yourproxy.domain.com:1234'

Hope it helps
```

**Comment by javiergarza** [comment]
@ellenbluth it will be great to have the HTTP_PROXY environment variables documented on the READ.me so people are aware how to use the Akamai CLI behind a proxy
